# Company
- title: "About"
  url: "/about-us/"
  section: "Company"

- title: "Partners"
  url: "/netlicensing/partners/"
  section: "Company"

- title: "Contact"
  url: "/contact/"
  section: "Company"

# Learn
- title: NetLicensing
  url: "https://netlicensing.io"
  section: "Documentation"

- title: Journal
  url: "https://netlicensing.io/blog/"
  section: "Documentation"

# Legal
- title: "Terms of Service"
  url: "/legal/terms-of-service/website/"
  section: "Legal"

- title: "Privacy Policy"
  url: "/legal/privacy-policy/"
  section: "Legal"

- title: "Cookies Policy"
  url: "/legal/privacy-policy/cookies-policy/"
  section: "Legal"

- title: "Imprint"
  url: "/imprint/"
  section: "Legal"
